# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58159cfc858f9d57a3725f24a08f2adeff7adf4ee82aa09b2a8c6de6ebbe9ff836331f0d1ea4b5d0aedfdc4b79aa47135986aafb32efc890f66a89b2e93246a4

test:
  secret_key_base: c9e693e588a3e7e16ab123e724adac3e715f62aacb71e4a6e8f7be19216e48a5508ba612b553dd9b9e6777f0d6041fa0f554bbc885f8f18c0b5e8b1afed8f5b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
